# Generated by Django 3.0.9 on 2023-10-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='robot_serial',
        ),
        migrations.AddField(
            model_name='order',
            name='model',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='version',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
    ]
